---

- name: ensure requirements are installed
  include_role:
    name: apt-meta
  vars:
    apt_packages:
      - "{{ i3_utils_systemd_shared_packages }}"

- name: ensure xlock is downloaded
  get_url:
    url: https://raw.githubusercontent.com/cytopia/i3-utils-bin/master/bin/xlock
    dest: /usr/local/bin/xlock
    mode: 0755
    force: yes
    timeout: 30
  register: task_result
  until: task_result | succeeded
  retries: 10
  delay: 5
  become: yes

- name: ensure systemd directories exist
  file:
    state: directory
    path: "{{ item }}"
    mode: 0755
  become: yes
  with_items:
    - "{{ i3_utils_systemd_systemd_base_path }}/system"
    - "{{ i3_utils_systemd_systemd_base_path }}/logind.conf.d"

- name: ensure i3-utils-systemd close-lid is downloaded
  get_url:
    url: https://raw.githubusercontent.com/cytopia/i3-utils-systemd/master/systemd/logind.conf.d/70-close_lid.conf
    dest: "{{ i3_utils_systemd_systemd_base_path }}/logind.conf.d/70-close_lid.conf"
    mode: 0644
    force: yes
    timeout: 30
  register: task_result
  until: task_result | succeeded
  retries: 10
  delay: 5
  become: yes

# suspend.service requires the current user to be set
- name: create temporary file
  tempfile:
    state: file
    suffix: temp
  changed_when: False
  check_mode: no
  register: i3_utils_systemd_tmp

- name: ensure i3-utils-systemd suspend is downloaded
  get_url:
    url: https://github.com/cytopia/i3-utils-systemd/raw/master/systemd/system/suspend.service
    dest: "{{ i3_utils_systemd_tmp.path }}"
    mode: 0644
    force: yes
    timeout: 30
  register: task_result
  until: task_result | succeeded
  retries: 10
  delay: 5
  changed_when: False
  check_mode: no

- name: set username
  command: whoami
  register: i3_utils_systemd_username
  check_mode: no
  changed_when: False

- name: ensure i3-utils-systemd suspend is using correct username
  lineinfile:
    path: "{{ i3_utils_systemd_tmp.path }}"
    regexp: '^User=REPLACE_ME$'
    line: "User={{ i3_utils_systemd_username.stdout }}"
  changed_when: False
  check_mode: no

- name: ensure i3-utils-systemd suspend is in place
  copy:
    src: "{{ i3_utils_systemd_tmp.path }}"
    dest: "{{ i3_utils_systemd_systemd_base_path }}/system/suspend.service"
    mode: 0644
  become: yes

- name: ensure temp file is removed
  file:
    state: absent
    path: "{{ i3_utils_systemd_tmp.path }}"
  changed_when: False
  check_mode: no
