---

python_2_required_apt_packages:
  - python2
  - python-pip
  - python-setuptools

python_3_required_apt_packages:
  - python3
  - python3-pip
  - python3-setuptools

python_2_required_pip_packages:
  - wheel

python_3_required_pip_packages:
  - wheel
