---

clipmenu_bin_path: /usr/local/bin

clipmenu_shared_packages:
  - rofi
  # dmenu
  - suckless-tools
  - xsel
  # Required to compile clipnotify
  - x11proto-core-dev
  - libx11-dev
  - libxfixes-dev
