---

- name: ensure requirements are installed
  include_role:
    name: apt-meta
  vars:
    apt_packages: "{{ i3blocks_modules_shared_packages }}"

- name: ensure ./local/share directory exists
  file:
    state: directory
    path: "{{ i3blocks_modules_path }}"
    mode: 0755
  check_mode: False

- name: ensure i3blocks-modules is cloned
  git:
    repo: https://github.com/cytopia/i3blocks-modules
    clone: True
    dest: "{{ i3blocks_modules_path }}"
    force: True
    update: True
    depth: 1
